config/routes.rb
Rails.application.routes.draw do
  get 'users/signin'
  get 'users/signup'
  get 'users/invilid'
  get 'users/status'
  post 'users/authenticate'
  get 'users/list'
  resources 'users'

  resources 'logins'
  

resources 'libraries'

end

app/models/library.rb
class Library < ActiveRecord::Base
end

app/models/login.rb
class Login < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only:[:show, :delete, :update, :edit]
  def new
    @library = Library.new
  end

  def show
  end

  def edit
    #@library = Library.find(params[:id])
  
  end

  def create
    @library = Library.new(library_params)
    respond_to do |format|
      if @library.save
        format.html{redirect_to libraries_path, notice: 'Book addded successfull'}
      format.json{render :show, status: :created, location: @library}
    else
      format.html{render 'new'}
      format.json{render json: @library.errors, status: :unprocessable_entity}
    end
  end
  end

  def update
  end

  def destroy
    @library = Library.find(params[:id])
    respond_to do |format|
    @library.destroy

    format.html{redirect_to libraries_path, notice: 'Book deleted successfully'}
    format.json{head :no_content}
  end
  end

  def index
    @libraries = Library.all

  end

end

private
def set_library
  @library = Library.find(params[:id])
  end

def library_params
  params.require(:library).permit(:bookName, :auther, :subject, :noofcopy)
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def signin
  	@login = Login.new
  end

  def signup
  	@signup = Login.new
  end

  def create
  	@

  end

  def show
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

before_action :set_student, only:[:show, :update, :destroy, :edit]

  def new
    @student = Student.new
  end

  def show
    @student = Student.find_by_id(params[:id])
  end

  def index
    @students = Student.all
  end

  def create
   
    @student = Student.new(student_params)
    #@student = Student.new(params[:student])
    respond_to do |format|
      if @student.save

        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }

      end
    end
  end
    def update 
      respond_to do |format|
        if @student.update(student_params)
          format.html{redirect_to @student, notic: 'student was updated'}
          format.json{head :no_content}
        end
      end
    end

    def destroy
      @student = Student.find(params[:id])
      @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
    end

  def student_params
    params.require(:student).permit(:name, :rollno, :program, :email)
  end

  private

  def set_student
    @student= Student.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only:[:show]

  def signin
  	@user = User.new
  end

  def signup
  	@user = User.new
  end

  def create



  	@user = User.new(user_params)
  	respond_to do |format|
  		if @user.save
  			format.html{redirect_to @user, notice: 'User was Successfully SignUp'}
  			format.json{render :signin, status: :created, location: @user}
  		end
  	end
  end

  def authenticate
    #puts 'xxxxxxxxxxxxxxxxxxxx', params[:user][:username].inspect
    #@user = User.find_by_username()
    #@username = params[:user][:username]
     if @user= User.find_by_username(params[:user][:username])
    respond_to do |format|
      if @user && @user.password == params[:user][:password]
        format.html{redirect_to users_status_path, notice: 'Congratulation!! You are login successfully'}
        format.json{render :status, status: :signed, location: users_status_path}
      else
        format.html{redirect_to users_status_path, notice: 'oops!! your type incorrect password'}
        format.json{render :status, status: :fail, location: users_status_path}
      end
    end
  else
      redirect_to users_status_path, alert: 'User does not exist'
  end
end
  def status
  end
  private

 def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user= User.find_by_username(params[:username])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link href="css/bootstrap.min.css" rel="stylesheet">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
`

</head>
<body>

  <div class="page-header"  style="background-color: silver; margin-top:0;">
  <h1>User Authentication Application <small>    SignIn/SignOut</small></h1>
</div>




 	<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<div id="#content" style="margin:25px">
<%= yield %>
</div>
</body>
</html>

app/views/libraries/_library.html.erb
<%= form_for(@library) do |l|%>
<div class="field">
	<%=l.label "Book Name"%></br>
	<%=l.text_field :bookName%>
</div>

<div class = "field">
	<%=l.label :auther%></br>
	<%=l.text_field :auther%>
</div>
<div class="field">
	<%=l.label "Subject"%></br>
	<%=l.text_field :subject%>
</div>

<div class = "field">
	<%=l.label "No Of Copy"%></br>
	<%=l.text_field :noofcopy%>
</div>

<p><%=l.submit %></p>
<%end%>

app/views/libraries/create.html.erb
<h1>Libraries#create</h1>
<p>Find me in app/views/libraries/create.html.erb</p>

app/views/libraries/delete.html.erb
<h1>Libraries#delete</h1>
<p>Find me in app/views/libraries/delete.html.erb</p>

app/views/libraries/edit.html.erb
<h1>Editting/Changing Book informaion</h1>
<%=render 'library'%>

app/views/libraries/index.html.erb
<h1>Book Listing</h1>
<table>
	<thead>
		<tr>
			<th>Name of Book</th>
			<th>Subject</th>
			<th>Auther</th>
			<th>No of Copies</th>
			<th colspan = 4></th>
		</td>
	</thead>


	

	<tbody>
		<%@libraries.each do |library|%>
		<tr>
			<td><%= library.bookName %></td>
			<td><%= library.subject %></td>
			<td><%= library.auther %></td>
			<td><%= library.noofcopy %></td>
			<td><%=link_to 'Show', library%></td>
			<td>&nbsp &nbsp | &nbsp &nbsp</td>
			<td><%= link_to 'Delete', library, method: :delete, data:{confirm: 'are you sure?'}%></td>
			<td>&nbsp &nbsp | &nbsp &nbsp</td>
			<td><%= link_to 'Edit', edit_library_path(library)%> </td>
		</tr>
			<%end%>
	</tbody>
</table>
</br></br>

<%=link_to "Add New Book To Libray" , new_library_path%>

app/views/libraries/new.html.erb
<h1>Book Registration Form</h1>
<%=render 'library'%>

app/views/libraries/show.html.erb
<h1>Libraries#show</h1>
<p>Find me in app/views/libraries/show.html.erb</p>

app/views/libraries/update.html.erb
<h1>Libraries#update</h1>
<p>Find me in app/views/libraries/update.html.erb</p>

app/views/logins/_form.html.erb
<h1>SignIn</h1>
<%=form_for @login do |f|%>
	<%=f.label "User name"%></br>
	<%=f.text_field :username%></br>
	<%=f.label "Password" %></br>
	<%=f.password_field :password%><br>
	<%=f.submit 'Signin'%>
	<%end%>

app/views/logins/show.html.erb
<h1>Logins#show</h1>
<p>Find me in app/views/logins/show.html.erb</p>

app/views/logins/signin.html.erb
<h1>SignIn</h1>
<%=form_for @login do |f|%>
	<%=f.label "User name"%></br>
	<%=f.text_field :username%></br>
	<%=f.label "Password" %></br>
	<%=f.password_field :password%><br>
	<%=f.submit 'Signin'%>
	<%end%>

app/views/logins/signup.html.erb
<h1>SignUp</h1><h1>SignIn</h1>
<%=form_for @signup do |f|%>
	<%=f.label "User name"%></br>
	<%=f.text_field :username%></br>
	<%=f.label "Email"%></br>
	<%=f.text_field :email%></br>
	<%=f.label "Password" %></br>
	<%=f.password_field :password%><br>

	<%=f.submit 'Signup'%>
	<%end%>

app/views/students/_form.html.erb
<%= form_for (@student) do |f| %>
<% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%=full_messages %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rollno %><br>
    <%= f.text_field :rollno %>
  </div>
  <div class="field">
    <%= f.label :program %><br>
    <%= f.text_field :program %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/destroy.html.erb
<p id="notice"><%= notice %></p>

app/views/students/edit.html.erb
<h3>Editing Student </h3>
<%= render 'form' %>

app/views/students/index.html.erb
<h1>Students List</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Roll No</th>
      <th>Program</th>
      <th>Emai.</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.rollno %></td>
        <td><%= student.program %></td>
        <td><%= student.email %></td>
        <td><%= link_to 'Show', student %></td>
        <td> &nbsp &nbsp | &nbsp &nbsp <td>
        <td><%= link_to 'Destroy', student, method: :delete, data: {confirm: 'are you sure?'}%> </td>
      </tr>
    <% end %>
  </tbody>
</table>
</br></br>
<%= link_to 'Create New Student', new_student_path %>

<br>

app/views/students/new.html.erb
<h3>Student Registration Form</h3>
<%= render 'form' %>

app/views/students/show.html.erb
<h1>Student Info</h1>
<p>Studnet Name:<%= @student.name%></p>
<p>Roll Number :<%= @student.rollno%></p>
<p>Study Prog  :<%= @student.program%></p>
<p>Email Add   :<%= @student.email%></p>
<%= link_to "index", students_path %>
<%= link_to "edit", edit_student_path(@student)%>
<%= link_to 'destroy', student_path, method: :delete, data:{confirm: 'are you sure, You want to delete this record?'}%>

app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>

app/views/users/invilid.html.erb
<h1>Login unsuccessfull</h1>

app/views/users/list.html.erb
<h1> list page here</h1>
<div class="dropdown">
  <button class="btn dropdown-toggle sr-only" type="button" id="dropdownMenu1" data-toggle="dropdown">
    Dropdown
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Action</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Another action</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Something else here</a></li>
    <li role="presentation" class="divider"></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Separated link</a></li>
  </ul>
</div>

app/views/users/signin.html.erb
<h1>SignIn</h1>
<%=form_for @user, :url => '/users/authenticate' do |f|%>
	<%=f.label "User name"%></br>
	<%=f.text_field :username, required: true%></br>
	<%=f.label "Password" %></br>
	<%=f.password_field :password, required: true%><br>
	<%=f.submit 'Signin'%></br>
	I don't have account <%= link_to 'Register', :action => 'signup' %>
	<%end%>

	<script>
	$('#new_user').validate({});

	</script>

app/views/users/signup.html.erb
<div class="container-fluid">

  <div class="row">

<h1>SignUp</h1>
<p class ="error"></p>


<%=form_for @user do |f|%>

	<%=f.label "User name"%></br>
	<%=f.text_field :username, required: true%><label id = "userName"></label></br>

	<%=f.label "Email"%></br>
	<%=f.text_field :email, required: true, email: true%> <!--<label id = "incorrectEmail"></label> --></br>


	<%=f.label "Password" %></br>
	<%=f.password_field :password, required: true, minlength: 6%><!--<label id = "incorrectPassword"></label> --></br>
	<%=f.label "Confirm Password" %></br>
	<%=password_field_tag 'confirm_password', nil, equalTo: "#user_password"%></br>

	<%=f.submit 'Signup'%></br>
	I have already account <%= link_to 'SignIn', :action => 'signin' %>
	<%end%>
  </div>
</div>
	<script type="text/javascript">	
$('#new_user').validate({});
	</script>